config/routes.rb
Rails.application.routes.draw do
  get 'realisations/show'
  ActiveAdmin.routes(self)
  devise_for :users, :skip => :registration
  root to: 'pages#home'
  resources :contacts
  resources :realisations
  resources :categories
  resources :pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorie.rb
class Categorie < ApplicationRecord
  has_many :realisations, dependent: :destroy
  has_one_attached :photo, dependent: :destroy

  validates :titre, presence: true
  validates :description, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :prenom, presence: true
  validates :nom, presence: true
  validates :description, presence: true
  validates :objet, presence: true
  validates :email, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :realisation
  has_one_attached :photo, dependent: :destroy
end

app/models/realisation.rb
class Realisation < ApplicationRecord
  belongs_to :user
  belongs_to :categorie
  has_many :pictures, dependent: :destroy
  # has_many_attached :photos, dependent: :destroy

  validates :titre, presence: true
  validates :description, presence: true
  validates :lieu, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :realisations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def show
    @categorie = Categorie.find(params[:id])
    @realisations = Realisation.select {|realisation| realisation["categorie_id"].to_i == @categorie.id }
  end
end

def article_params
  params.require(:categorie).permit(:titre, :description, :photo)
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  after_action :send_mail, only: :create

  def new
    @contact = Contact.new
    @objets = ['Demande de devis', 'Demande d\'information', 'Prise de contact professionnelle']
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:nom, :prenom, :email, :telephone, :objet, :description)
  end

  def send_mail
    ContactMailer.with(contact: self).contact_message(@contact).deliver_now
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :contact]
  def home
    @categories = Categorie.all
  end
end

app/controllers/realisations_controller.rb
class RealisationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def show
    @realisation = Realisation.find(params[:id])
  end

  def new
    @realisation = Realisation.new
  end

  def create
    @realisation = Realisation.new(product_params)
    if @realisation.save
      create_pictures
      redirect_to realisation_path(@realisation)
    else
      render :new
    end
  end

  private

  def create_pictures
    photos = params.dig(:realisation, :pictures) || []
    photos.each do |photo|
      @realisation.pictures.create(photo: photo)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<div class="banner-categorie mb-5", style="background-image: url('<%= cl_image_path @categorie.photo.key %>')">
</div>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-10 text-center p-4 mb-5 mt-3 categorie-description">
      <h1><%= @categorie.titre %></h1>
      <p><%= @categorie.description %></p>
      <%= image_tag ("https://res.cloudinary.com/dkrtmft3y/image/upload/v1588681058/logo-artisan_pef0jm.png"), class: "img-responsive mb-1 mt-2"%>
    </div>
</div>
<hr class="mb-5">
<div class="container-fluid">
  <% @realisations.each_with_index do |realisation, index| %>
    <div class="row justify-content-center pt-4 pb-4">
      <% if index == 0 || index % 2 == 0 %>
      <div class="col-lg-10 realisation-card align-right slide-in">
        <div class="realisation-description text-center p-5">
          <h2><%= realisation.titre %></h2>
          <h3><%= realisation.lieu %></h3>
          <p><%= realisation.description %></p>
          <%= link_to "Voir galerie", realisation_path(realisation), class: "btn-home" %>
        </div>
        <div class="realisation-image">
          <%= cl_image_tag realisation.pictures.first.photo.key, crop: :fill, class: "img-responsive" %>
        </div>
      </div>
      <% else %>
      <div class="col-lg-10 realisation-card align-left slide-in">
        <div class="realisation-image">
          <%= cl_image_tag realisation.pictures.first.photo.key, crop: :fill, class: "img-responsive" %>
        </div>
        <div class="realisation-description text-center p-5">
          <h2><%= realisation.titre %></h2>
          <h3><%= realisation.lieu %></h3>
          <p><%= realisation.description %></p>
          <%= link_to "Voir galerie", realisation_path(realisation), class: "btn-home" %>
        </div>
      <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center p-3">
    <div class="col-lg-12 contact-page">
      <div class="form">
        <h1 class="text-center mb-3">Me contacter</h1>
        <%= simple_form_for(@contact) do |f| %>
          <%= f.input :nom, :label => "Nom", required: true, autofocus: true %>
          <%= f.input :prenom, :label => "Prénom", required: true, autofocus: true %>
          <%= f.input :email, :label => "Email", required: true %>
          <%= f.input :telephone, :label => "Numéro de téléphone" %>
          <%= f.input :objet, :collection => @objets, :label => "Sélectionner un objet...", required: true %>
          <%= f.input :description, :label => "Décrivez votre demande", required: true %>
          <div class="text-center">
            <%= f.submit "Envoyer", class: "btn btn-primary mt-4"%>
          </div>
        <% end %>
      </div>
      <div class="contact-photo">
        <%= image_tag ("https://images.unsplash.com/photo-1531220674280-b18cf8650cf3?ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"), class: "img-responsive d-block w-100"%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Valentin Guiol Ferronnerie et Création</title>
    <meta property="og:title" content="Valentin Guiol Ferronnerie et Création" />
    <meta property="og:description" content="Valentin Guiol Ferronnerie et Création, ferronnerie d'art en Provence, conception artisanale sur mesure" />
    <meta property="og:url" content="https://www.vgferronneriecreation.com/" />
    <meta property="og:type" content="Site web" />
    <meta property="og:image" content="./app/assets/images/favicon.ico" />
    <%= favicon_link_tag 'favicon-32x32.png' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-home mb-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8 banner-content">
        <h1 style="font-size: 32px;">Vos projets sur mesures avec un travail d'artisan</h1>
        <p class="text-justify mt-3">VG FERRONNERIE CREATION propose un éventail de réalisations selon votre demande. Garde Corps, verrières, pergolas, portes, portails, mobiliers et bien d’autres. L’acier se transforme... Une idée? VG FERRONNERIE peut créer pour vous les aménagements de vos envies.</p>
        <div class="text-right mt-4">
          <%= link_to "Devis gratuit", new_contact_path, class: "btn-home mt-3" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row mb-5 mr-4 ml-4 align-top slide-in">
    <div class="col-md-3 pt-4 business-spec">
      <%= image_tag ("https://res.cloudinary.com/vg-ferronnerie/image/upload/v1589880031/001-steel_q9xf2t.png"), class: "img-responsive mb-3"%>
      <h2>Conception<br>artisanale</h2>
    </div>
    <div class="col-md-3 pt-4 business-spec">
      <%= image_tag ("https://res.cloudinary.com/vg-ferronnerie/image/upload/v1589880004/004-ruler_mmzr5d.png"), class: "img-responsive mb-3"%>
      <h2>Réalisation<br>sur mesure</h2>
    </div>
    <div class="col-md-3 pt-4 business-spec">
      <%= image_tag ("https://res.cloudinary.com/vg-ferronnerie/image/upload/v1589880003/002-crown_ekqy5r.png"), class: "img-responsive mb-3"%>
      <h2>Service<br>de qualité</h2>
    </div>
    <div class="col-md-3 pt-4 business-spec">
      <%= image_tag ("https://res.cloudinary.com/vg-ferronnerie/image/upload/v1589880046/003-help_pfol5a.png"), class: "img-responsive mb-3"%>
      <h2>Conseils<br>personnalisés</h2>
    </div>
  </div>
</div>
<hr id="artisan" class="mb-5">
<div class="container artisan-presentation align-top slide-in">
  <div class="row mb-5 pt-4 pb-4 mr-1 ml-1">
    <div class="col-md-6 col-sm-12 presentation text-center">
      <h2 class="mb-3">L'artisan, du dessin à la conception</h2>
      <p>Je m’appelle Valentin GUIOL. Après près de dix ans d'expérience dans le monde de la métallerie, passionné de mon travail, je me suis lancé à mon compte depuis Septembre 2019.<br>
La ferronnerie amène à dessiner des plans, se projeter, réaliser et installer des oeuvres uniques pour ma plus grande satisfaction ainsi que celle de la clientèle.
Ce métier est en perpétuel mouvement de mode. Du style ancien au design, la ferronnerie me permet de m’épanouir et de découvrir l’étendu de mes capacités.</p>
      <%= image_tag ("https://res.cloudinary.com/vg-ferronnerie/image/upload/v1589880001/logo-artisan_o2djet.png"), class: "img-responsive mb-3 mt-3"%>
    </div>
    <div class="col-md-6 col-sm-12 col-xs-12">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag ("https://res.cloudinary.com/vg-ferronnerie/image/upload/v1593030031/artisan-1_d7hq0m.jpg"), class: "d-block img-responsive w-100"%>
          </div>
          <div class="carousel-item">
            <%= image_tag ("https://res.cloudinary.com/vg-ferronnerie/image/upload/v1593030031/artisan-2_rejai0.jpg"), class: "d-block img-responsive w-100"%>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>
<hr class="mb-5">
<div class="container-fluid pr-5 pl-5 text-center align-top slide-in">
  <h2>Mes Réalisations</h2>
  <div class="mt-5">
    <div class="categorie-cards">
    <% @categories.each do |categorie| %>
    <%= link_to category_path(categorie) do %>
      <div class="card" style="background-image: url('<%= cl_image_path categorie.photo.key, crop: :fit%>')">
        <div class="overlay">
          <div class = "items head ml-3">
            <p><%= categorie.titre %></p>
            <hr>
          </div>
          <div class="mt-5"></div>
        </div>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/realisations/show.html.erb
<div class="container-fluid p-5">
  <div class="row pt-5 pr-5 pl-5 pb-2">
    <div class="real-specs">
      <div class="col-md-12 specs pr-5 pl-5">
        <h1 class="mb-3"><%= @realisation.titre %></h1>
        <h2><%= @realisation.lieu %></h2>
        <p><%= @realisation.description %></p>
      </div>
      <%= image_tag ("https://res.cloudinary.com/dkrtmft3y/image/upload/v1588681058/logo-artisan_pef0jm.png"), class: "img-responsive mr-4"%>
    </div>
  </div>
  <hr class="mb-5 mt-5">
  <div class="row p-5">
    <div class="col-md-12">
      <div class="carousel js-flickity">
        <% @pictures = @realisation.pictures %>
        <% @pictures.each do |picture| %>
        <div class="carousel-cell">
          <%= cl_image_tag picture.photo.key, crop: :fill, class: "img-responsive" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-specs">
    <p>VG Ferronnerie et création</p>
    <p>N°SIREN : 853279271</p>
    <p>N°SIRET : 853 279 27100011</p>
  </div>
  <div class="footer-contact">
    <p>Valentin Guiol</p>
    <p>06.18.50.34.93</p>
    <a href="https://instagram.com/valentin_guiol?igshid=1x9p3be7bcy8b" target="_blanck"><i class="fab fa-instagram"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- <div class="navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dkrtmft3y/image/upload/v1589285240/Logo-VGferronerie_bfrf9v.png", class: "img-responsive" %>
  <% end %>


  <div class="links">

          <div class="dropdown">
            <p class="navbar-link dropdown-toggle mb-0" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Réalisations
            </p>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
              <% @categories = Categorie.all %>
              <% @categories.each do |categorie| %>
                <%= link_to categorie.titre, category_path(categorie), class: "dropdown-item" %>
              <% end %>
            </div>
          </div>
          <% if params[:action] == ('show') || current_page?(new_contact_path) %>
            <%= link_to "L'artisan", root_path, class: "navbar-link" %>
          <% else %>
            <%= link_to "L'artisan", "#artisan", class: "navbar-link" %>
          <% end %>
          <%= link_to "Contact", new_contact_path, class: "navbar-link" %>

    </ul>
  </div>
</div> -->

      <header class="header">
        <%= link_to root_path, class: "logo" do %>
          <%= image_tag "https://res.cloudinary.com/dkrtmft3y/image/upload/v1589285240/Logo-VGferronerie_bfrf9v.png", class: "img-responsive" %>
        <% end %>
        <input class="menu-btn" type="checkbox" id="menu-btn" />
        <label class="menu-icon" for="menu-btn"><span class="navicon"></span></label>
        <ul class="menu">
          <li>
            <div class="dropdown">
              <p class="dropdown-toggle mb-0" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Réalisations
              </p>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                <% @categories = Categorie.all %>
                <% @categories.each do |categorie| %>
                  <%= link_to categorie.titre, category_path(categorie), class: "dropdown-item" %>
                <% end %>
              </div>
            </div>
          </li>
          <li>
            <% if params[:action] == ('show') || current_page?(new_contact_path) %>
              <%= link_to "L'artisan", root_path %>
            <% else %>
              <%= link_to "L'artisan", "#artisan" %>
            <% end %>
          </li>
          <li>
            <%= link_to "Contact", new_contact_path %>
          </li>
        </ul>
      </header>